## Model Building: Predict Musuems' Ratings  
Author: Anne Chen  
2016

In [1]:
import numpy as np
import pandas as pd
from fancyimpute import KNN

Using Theano backend.

In [2]:
m_dum = pd.read_csv("dummified_df.csv")
m_dum.head()

,Unnamed: 0,Address,Description,FeatureCount,Fee,Langtitude,Latitude,LengthOfVisit,MuseumName,PhoneNum,...,descri_pol,descri_sub,LengthOfVisit__1-2 hours,LengthOfVisit__2-3 hours,LengthOfVisit__<1 hour,LengthOfVisit__More than 3 hours,Country__Other,Country__USA,Fee__No,Fee__Yes
0,0,"555 Pennsylvania Ave NW, Washington DC, DC 200...",Find out for yourself why everyone is calling ...,3.0,Yes,-77.019235,38.893138,2-3 hours,Newseum,+1 888-639-7386,...,0.490000,0.506667,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
1,4,"1000 5th Ave, New York City, NY 10028-0198",At New York City's most visited museum and att...,12.0,Yes,-73.962928,40.779166,2-3 hours,The Metropolitan Museum of Art,1 212-535-7710,...,0.318182,0.477273,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
2,5,"945 Magazine Street, New Orleans, LA 70130-3813","Founded by historian and author, Stephen Ambro...",11.0,NaN,-90.070086,29.943004,NaN,The National WWII Museum,+1 504-528-1944,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,6,"2001 N Colorado Blvd, Denver, CO 80205-5798",The Denver Museum of Nature & Science is the R...,0.0,NaN,-104.941020,39.769189,NaN,Denver Museum of Nature & Science,303-370-6000,...,0.100000,0.400000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,7,"111 S Michigan Ave, Chicago, IL 60603-6488","This Classical Renaissance structure, guarded ...",5.0,Yes,-87.623724,41.879547,More than 3 hours,Art Institute of Chicago,312 443 3600,...,0.300000,0.337500,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [3]:
col_idx_df = pd.DataFrame({'colname':m_dum.columns.values})
col_idx_df
# idx to drop: [0,1,2,4,5,6,7,8,9,14,15]

                               colname
0                           Unnamed: 0
1                              Address
2                          Description
3                         FeatureCount
4                                  Fee
5                           Langtitude
6                             Latitude
7                        LengthOfVisit
8                           MuseumName
9                             PhoneNum
10                                Rank
11                              Rating
12                         ReviewCount
13                     TotalThingsToDo
14                             Country
15                               State
16                      RankPercentage
17                       Ancient Ruins
18             Architectural Buildings
19                   Arenas & Stadiums
20                       Art Galleries
21                         Art Museums
22                    Auto Race Tracks
23                             Ballets
24                        Battlefields
25                       Biking Trails
26                     Bodies of Water
27                             Bridges
28                             Castles
29                          Cemeteries
..                                 ...
202                         Solo_Count
203                     Business_Count
204                      Friends_Count
205                      PreciseRating
206                      quote_pol_var
207                     quote_pol_mean
208                      quote_pol_max
209                      quote_pol_min
210                      quote_sub_var
211                     quote_sub_mean
212                      quote_sub_max
213                      quote_sub_min
214                     review_pol_var
215                    review_pol_mean
216                     review_pol_max
217                     review_pol_min
218                     review_sub_var
219                    review_sub_mean
220                     review_sub_max
221                     review_sub_min
222                         descri_pol
223                         descri_sub
224          LengthOfVisit__1-2 hours
225          LengthOfVisit__2-3 hours
226            LengthOfVisit__<1 hour
227  LengthOfVisit__More than 3 hours
228                     Country__Other
229                       Country__USA
230                           Fee__No
231                          Fee__Yes

[232 rows x 1 columns]

In [4]:
# drop columns that are irrevelant to modeling 
# and original categorical features which had beend dummified
# columns of interest: column index 11 'Rating' OR column index 64 'PreciseRating'
# dataframe w/ displayed rating 
idx_to_drop = [0,1,2,4,5,6,7,8,9,14,15]
museum_d = m_dum.drop(m_dum.columns[idx_to_drop + [64]], axis=1)
# dataframe w/ precise rating
museum_p = m_dum.drop(m_dum.columns[idx_to_drop + [11]], axis=1)

In [5]:
museum_d.describe() # descri_pol and descri_sub have NAs

/Users/annecool37/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,FeatureCount,Rank,Rating,ReviewCount,TotalThingsToDo,RankPercentage,Ancient Ruins,Architectural Buildings,Arenas & Stadiums,Art Galleries,...,descri_pol,descri_sub,LengthOfVisit__1-2 hours,LengthOfVisit__2-3 hours,LengthOfVisit__<1 hour,LengthOfVisit__More than 3 hours,Country__Other,Country__USA,Fee__No,Fee__Yes
count,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,...,1161.000000,1161.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000,1603.000000
mean,1.007486,16.555209,4.426700,1540.467249,243.429195,9.297117,0.001248,0.006862,0.001871,0.006862,...,0.179419,0.397966,0.149719,0.123518,0.021834,0.054273,0.388022,0.611978,0.032439,0.115409
std,2.149806,28.900707,0.285016,3906.633803,308.115561,10.134265,0.035311,0.082579,0.043234,0.082579,...,0.185510,0.221829,0.356907,0.329134,0.146187,0.226627,0.487452,0.487452,0.177219,0.319614
min,0.000000,1.000000,2.500000,32.000000,1.000000,0.069300,0.000000,0.000000,0.000000,0.000000,...,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,4.500000,213.000000,48.000000,2.941176,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,6.000000,4.500000,510.000000,142.000000,6.250000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,1.000000,19.000000,4.500000,1257.000000,314.500000,12.500000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
max,27.000000,397.000000,5.000000,63112.000000,2279.000000,100.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
museum_d.describe().to_csv('summary_before_imputation.csv')

In [7]:
museum_d.columns

Index([u'FeatureCount', u'Rank', u'Rating', u'ReviewCount', u'TotalThingsToDo',
       u'RankPercentage', u'Ancient Ruins', u'Architectural Buildings',
       u'Arenas & Stadiums', u'Art Galleries',
       ...
       u'descri_pol', u'descri_sub', u'LengthOfVisit__1-2 hours ',
       u'LengthOfVisit__2-3 hours ', u'LengthOfVisit__<1 hour ',
       u'LengthOfVisit__More than 3 hours ', u'Country__Other',
       u'Country__USA', u'Fee__No ', u'Fee__Yes '],
      dtype='object', length=220)

### Exploring Different Models - Multilinear Regression and Random Forest

In [8]:
from sklearn.cross_validation import train_test_split
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

In [9]:
# m_x = museum_d.drop(museum_d.columns[[2]], axis=1) # drop rating
# m_y = museum_d['Rating']
# m_x = df.drop(df.columns[[193]], axis=1) # drop PreciseRating
# m_y = df['PreciseRating']
def explore_model(df, col_name_to_pred, col_idx_to_drop):
    np.random.seed(0)
    m_x = df.drop(df.columns[[col_idx_to_drop]], axis=1) 
    m_y = df[col_name_to_pred]
    n_samples = m_x.shape[0]
    n_features = m_x.shape[1]
    print 'number of samples:', n_samples
    print 'number of features', n_features
    
    # subset training and testing
    x_train, x_test, y_train, y_test = train_test_split(m_x, m_y, test_size=0.2, random_state = 0)
    
    # linear regression
    ols = linear_model.LinearRegression()
    ols.fit(x_train, y_train)

    print 'multilinear score:', ols.score(x_train, y_train)
    predicted = ols.predict(x_test)
    print 'multilinear MSE:', np.mean((predicted - y_test)**2)

    # store coefficients
    coef_linear = pd.DataFrame({'feature':m_x.columns, 'coef': ols.coef_})
    coef_linear = coef_linear.sort_values(by = 'coef', axis=0, ascending = False)
    
    # random forest (regression)
    rf = RandomForestRegressor()
    rf.fit(x_train, y_train)
    print 'random forest (regression) score:', rf.score(x_train, y_train)
    predicted = rf.predict(x_test)
    print 'random forest (regression) MSE:', np.mean((predicted - y_test)**2)
    
    # random forest (classification
    # convert predictor from numeric into string
    y_train = [str(i) for i in y_train]
    y_test = [str(i) for i in y_test]        
    np.random.seed(0)
    rf_c = RandomForestClassifier()
    rf_c.fit(x_train, y_train)
    predicted = rf_c.predict(x_test)
    err = 1 - np.mean(predicted == y_test)
    print 'random forest (classification) score:', rf_c.score(x_train, y_train)
    predicted = rf_c.predict(x_test)
    print 'random forest (classification) error:', err
    
    # feature importance
    feature_imprtance = zip(m_x.columns, rf.feature_importances_)
    dtype = [('feature', 'S10'), ('importance', 'float')]
    feature_imprtance = np.array(feature_imprtance, dtype = dtype)
    feature_sort = np.sort(feature_imprtance, order='importance')[::-1]
    print 'RF regression'
    print 'top 10 important features:'
    print feature_sort[0:10]
    
    feature_imprtance_c = zip(m_x.columns, rf_c.feature_importances_)
    dtype = [('feature', 'S10'), ('importance', 'float')]
    feature_imprtance_c = np.array(feature_imprtance_c, dtype = dtype)
    feature_sort_c = np.sort(feature_imprtance_c, order='importance')[::-1]
    print 'RF Classification'
    print 'top 10 important features:'
    print feature_sort_c[0:10]
    
    return coef_linear, feature_sort, feature_sort_c

In [10]:
def cv_rf_class(k_grid, df, col_name_to_pred, col_idx_to_drop):
    err_lst = []
    score_lst = []
    length = df.shape[0]
    for k_val in k_grid:
        X_filled_knn = KNN(k = k_val).complete(df)
        knn_imputed_md = pd.DataFrame(data = X_filled_knn,
                                      index= range(0,length),
                                      columns = df.columns)
        
        m_x = knn_imputed_md.drop(knn_imputed_md.columns[[col_idx_to_drop]], axis=1)        
        m_y = [str(i) for i in knn_imputed_md[col_name_to_pred]]
        x_train, x_test, y_train, y_test = train_test_split(m_x, m_y, test_size=0.2, random_state = 0)        
        np.random.seed(0)
        rf = RandomForestClassifier()
        rf.fit(x_train, y_train)
        predicted = rf.predict(x_test)
        score_lst.append(rf.score(x_train, y_train))
        err_lst.append(1 - np.mean(predicted == y_test))
    result_df = pd.DataFrame({'k':k_grid, 'score':score_lst, 'error':err_lst})  
    result_df = result_df.sort_values(by = 'error', axis=0)
    return result_df

def cv_rf_regres(k_grid, df, col_name_to_pred, col_idx_to_drop):
    mse_lst = []
    score_lst = []
    length = df.shape[0]
    for k_val in k_grid:
        X_filled_knn = KNN(k = k_val).complete(df)
        knn_imputed_md = pd.DataFrame(data = X_filled_knn,
                                      index= range(0,length),
                                      columns = df.columns)
        m_x = knn_imputed_md.drop(knn_imputed_md.columns[[col_idx_to_drop]], axis=1)
        m_y = knn_imputed_md[col_name_to_pred]
        np.random.seed(0)
        rf = RandomForestRegressor()            
        x_train, x_test, y_train, y_test = train_test_split(m_x, m_y, test_size=0.2, random_state = 0)
        rf.fit(x_train, y_train)
        predicted = rf.predict(x_test)
        score_lst.append(rf.score(x_train, y_train))
        mse_lst.append(np.mean((predicted - y_test)**2))
    result_df = pd.DataFrame({'k':k_grid, 'score':score_lst, 'mse':mse_lst})  
    result_df = result_df.sort_values(by = 'mse', axis=0)
    return result_df

## Prediction: Displayed Rating & Precise Rating 
missing values are handled with mean or knn imputation

#### Mean Imputation

In [11]:
# imput NA with mean value
mean_impute_d = museum_d.copy(deep = True)
mean_impute_p = museum_p.copy(deep = True)

mean_impute_d['descri_pol'] = museum_d['descri_pol'].fillna(np.mean(museum_d['descri_pol']))
mean_impute_d['descri_sub'] = museum_d['descri_sub'].fillna(np.mean(museum_d['descri_sub']))

mean_impute_p['descri_pol'] = museum_p['descri_pol'].fillna(np.mean(museum_p['descri_pol']))
mean_impute_p['descri_sub'] = museum_p['descri_sub'].fillna(np.mean(museum_p['descri_sub']))

In [12]:
explore_model(mean_impute_d,'Rating',[2, 193])

number of samples: 1603
number of features 218
multilinear score: 0.473653183562
multilinear MSE: 0.0609866180954
random forest (regression) score: 0.876169452672
random forest (regression) MSE: 0.0568535825545
random forest (classification) score: 0.983619344774
random forest (classification) error: 0.274143302181
RF regression
top 10 important features:
[('Rank', 0.24679201964963987) ('RankPercen', 0.10720257468757007)
 ('review_pol', 0.046074096716786826) ('quote_sub_', 0.04212617145547866)
 ('review_pol', 0.02964226445210446) ('ReviewCoun', 0.02958528532914046)
 ('Friends_Co', 0.026058881882098005) ('Couples_Co', 0.0227666079291552)
 ('quote_pol_', 0.02177004983768878) ('quote_pol_', 0.02066406826032283)]
RF Classification
top 10 important features:
[('RankPercen', 0.06266225594213995) ('Rank', 0.04739976579805334)
 ('review_pol', 0.03947451085555946) ('TotalThing', 0.0381469799115917)
 ('quote_sub_', 0.037377531721634195) ('review_pol', 0.031844117807274065)
 ('review_pol', 0.030730587539327774) ('review_pol', 0.030622952804746844)
 ('quote_sub_', 0.028980796461515756) ('quote_pol_', 0.028823043190663578)]

(         coef                      feature
 192  1.015978                quote_pol_var
 45   0.592839                        Mines
 7    0.483363            Arenas & Stadiums
 66   0.413150         Scenic Walking Areas
 34   0.356770       Historic Walking Areas
 196  0.346120                quote_sub_var
 68   0.323701  Self-Guided Tours & Rentals
 15   0.321999                      Bridges
 201  0.302699              review_pol_mean
 5    0.280447                Ancient Ruins
 195  0.201537                quote_pol_min
 83   0.192732                Walking Tours
 63   0.152497                Private Tours
 32   0.151410         Government Buildings
 39   0.151267                    Libraries
 11   0.140921                      Ballets
 19   0.117721                   City Tours
 84   0.114223         Wineries & Vineyards
 27   0.114223                 Food & Drink
 23   0.109787               Cultural Tours
 119  0.107114           amazing collection
 54   0.102102                    Nightlife
 21   0.102102                 Coffeehouses
 202  0.100171               review_pol_max
 47   0.089956               Movie Theaters
 149  0.082754                 worth a stop
 166  0.079642                   early days
 151  0.079332              stuffed animals
 135  0.078915                 works of art
 22   0.078516             Concerts & Shows
 ..        ...                          ...
 171 -0.063816                     displays
 100 -0.065299                  audio guide
 104 -0.071819         interesting exhibits
 6   -0.073297      Architectural Buildings
 162 -0.077864             large collection
 82  -0.079696                     Volcanos
 117 -0.080430                     his life
 48  -0.084251                      Museums
 129 -0.084950                   art lovers
 81  -0.091786              Visitor Centers
 207 -0.092133               review_sub_min
 37  -0.095226                      Islands
 67  -0.100435              Science Museums
 12  -0.110595                 Battlefields
 160 -0.112389                 a lot of fun
 52  -0.122830                Neighborhoods
 16  -0.134343                      Castles
 57  -0.134840            Other Fun & Games
 35  -0.152465  Historical & Heritage Tours
 193 -0.167175               quote_pol_mean
 14  -0.168135              Bodies of Water
 73  -0.169094             Sports Complexes
 80  -0.170081                      Valleys
 43  -0.203973  Military Bases & Facilities
 28  -0.213978                  Fun & Games
 55  -0.353992   Observation Decks & Towers
 60  -0.396107           Piers & Boardwalks
 17  -0.442344                   Cemeteries
 30  -0.471892          Geologic Formations
 200 -1.538978               review_pol_var

 [218 rows x 2 columns],
 array([('Rank', 0.24679201964963987), ('RankPercen', 0.10720257468757007),
        ('review_pol', 0.046074096716786826),
        ('quote_sub_', 0.04212617145547866),
        ('review_pol', 0.02964226445210446),
        ('ReviewCoun', 0.02958528532914046),
        ('Friends_Co', 0.026058881882098005),
        ('Couples_Co', 0.0227666079291552),
        ('quote_pol_', 0.02177004983768878),
        ('quote_pol_', 0.02066406826032283),
        ('Business_C', 0.019468149282285633),
        ('review_sub', 0.018673106040581575),
        ('quote_pol_', 0.018409370476824796),
        ('TotalThing', 0.017702009464608804),
        ('review_sub', 0.01768874377411308),
        ('quote_sub_', 0.01757113723369944),
        ('descri_pol', 0.017104658839655985),
        ('review_pol', 0.016395242707446932),
        ('Solo_Count', 0.015666635813303548),
        ('review_sub', 0.014887348810779702),
        ('quote_pol_', 0.014458765447220395),
        ('Families_C', 0.014363777273495141),
        ('review_pol', 0.014049246169072282),
        ('descri_sub', 0.013642289138274529),
        ('review_sub', 0.012865096170900672),
        ('amazing co', 0.009166174241164605),
        ('Country__U', 0.008006445940013474),
        ('Country__O', 0.0070459494151392296),
        ('quote_sub_', 0.005950905902729534),
        ('two hours', 0.00522745113276824),
        ('on display', 0.004839795830760419),
        ('van gogh', 0.004836161941396577),
        ('private co', 0.004755678479005059),
        ('Specialty ', 0.003612553368688172),
        ('FeatureCou', 0.0033638065148248264),
        ('galleries', 0.0033459256996368806),
        ('Science Mu', 0.003087329289453038),
        ('permanent ', 0.0029035017141312096),
        ('worth a vi', 0.0027702744700879066),
        ('history', 0.0025720325902231535),
        ('Arenas & S', 0.0025474970754499767),
        ('Fee__Yes ', 0.0024769824540372934),
        ('Cultural T', 0.0024400071628635275),
        ('displays', 0.0023761449072586182),
        ('gift shop', 0.002124002566891982),
        ('free admis', 0.002113503819901338),
        ('chronologi', 0.001923687207989465),
        ('entrance f', 0.0018164525846912703),
        ('suggested ', 0.0018136209283490159),
        ('his life', 0.0017685545102709554),
        ('Natural Hi', 0.0017363178568752676),
        ('great hist', 0.0016967243652577274),
        ('learn some', 0.0016448716245742296),
        ('LengthOfVi', 0.0015318880728364972),
        ('worth the ', 0.0015293589057159746),
        ('LengthOfVi', 0.001514931041802911),
        ('Walking To', 0.0014913605159751165),
        ('Cemeteries', 0.0014616704649731854),
        ('interestin', 0.0014568702109019767),
        ('History Mu', 0.001444849278942674),
        ('quote_sub_', 0.0013670023757326125),
        ('scavenger ', 0.0013514151734566418),
        ('a lot of f', 0.0013078542547222322),
        ('Nature & P', 0.0012966468833234175),
        ('Fun & Game', 0.0012918884636525573),
        ('great muse', 0.0012900066992266638),
        ('eye openin', 0.0012614235070453257),
        ('admission', 0.001218761400686929),
        ('worth a st', 0.0011993836845008282),
        ('civil war', 0.001193706267662379),
        ('interestin', 0.0011933373522482519),
        ('great coll', 0.0011726480210642106),
        ('local hist', 0.0011606543926493765),
        ('life size', 0.0011428210100875539),
        ('great plac', 0.0011325117741934983),
        ('world war', 0.00111282319459309),
        ('museums', 0.001094532969562059),
        ('beautiful ', 0.001060067375738017),
        ('small muse', 0.000991991377433575),
        ('LengthOfVi', 0.0009406526539251576),
        ('history bu', 0.0009147755546584206),
        ('lots of hi', 0.000903336181131542),
        ('Museums', 0.0008721436434233207),
        ('sculpture ', 0.000849502262906594),
        ('hands on a', 0.000822671216729275),
        ('artifacts', 0.0008096476146529231),
        ('interestin', 0.0008090290589845915),
        ('self guide', 0.0008025265477522451),
        ('the lower ', 0.0007987679575147758),
        ('Art Museum', 0.0007895158329605566),
        ('works of a', 0.0007664251326978195),
        ('for sale', 0.0007633965380680508),
        ('extensive ', 0.0007548509844760655),
        ('Tours', 0.0007425462005238596),
        ('guided tou', 0.0007303614228608579),
        ('great plac', 0.000725229093854061),
        ('LengthOfVi', 0.0007226960632685865),
        ('second flo', 0.0007075532006580167),
        ('great exhi', 0.0006713513505692628),
        ('interactiv', 0.000650389023185252),
        ('Movie Thea', 0.0006361078144072761),
        ('three hour', 0.0006162996709096751),
        ('collection', 0.0005473512576293657),
        ('step back ', 0.0005436317827385506),
        ('take pictu', 0.0005067612565799876),
        ('free entry', 0.0004979056988465307),
        ('well worth', 0.0004955506827101499),
        ('Historic S', 0.0004892334768607391),
        ('Monuments ', 0.0004839313150411228),
        ('old west', 0.0004763539923547475),
        ("Children's", 0.0004752023375543711),
        ('Ancient Ru', 0.0004734913571900701),
        ('art lovers', 0.0004658253911779272),
        ('walk aroun', 0.0004555655869416103),
        ('own pace', 0.00044712626152877113),
        ('stuffed an', 0.0004460459421440935),
        ('third floo', 0.0004422901638544658),
        ('rotating e', 0.00041654718182379806),
        ('take your ', 0.000399842801867827),
        ('top floor', 0.0003978379489107114),
        ('across the', 0.0003726386000798628),
        ('interactiv', 0.0003563235151499094),
        ('Gardens', 0.00034638824645714114),
        ('changing e', 0.00034235817322636865),
        ('special ex', 0.0003378654288099758),
        ('exhibits', 0.0003196606510455269),
        ('Traveler R', 0.00029316833703934073),
        ('few hours', 0.000292931024051752),
        ('great for ', 0.0002891275174910811),
        ('moving exp', 0.00028533087263358126),
        ('kids and a', 0.0002718265603746855),
        ('history le', 0.0002624462107322893),
        ('audio tour', 0.00023974548828415787),
        ('traveling ', 0.0002349790633861751),
        ('Fee__No ', 0.0002260202899427186),
        ('Points of ', 0.00022376245573185738),
        ('Historical', 0.00021597431543108128),
        ('Geologic F', 0.0002158950712833048),
        ('special ex', 0.00020895797002416615),
        ('whole fami', 0.0002031903879671076),
        ('natural hi', 0.000202284648898809),
        ('Architectu', 0.00019675843959957823),
        ('rainy day', 0.00018907751411149118),
        ('nice colle', 0.0001695170119180277),
        ('short film', 0.00012306924324894853),
        ('couple of ', 0.00012130869561926523),
        ('early days', 0.00011842512086219766),
        ('all ages', 0.00011344650846689729),
        ('Military M', 0.00010689807685144688), ('well worth', 0.0),
        ('we spent h', 0.0), ('three floo', 0.0), ('old master', 0.0),
        ('modern art', 0.0), ('large coll', 0.0), ('informatio', 0.0),
        ('great disp', 0.0), ('entry fee', 0.0), ('enjoyed ou', 0.0),
        ('audio guid', 0.0), ('american h', 0.0), ('Zoos & Aqu', 0.0),
        ('Zipline & ', 0.0), ('Wineries &', 0.0), ('Volcanos', 0.0),
        ('Visitor Ce', 0.0), ('Valleys', 0.0), ('Transporta', 0.0),
        ('Tramways', 0.0), ('Theaters', 0.0), ('State Park', 0.0),
        ('Sports Com', 0.0), ('Sights & L', 0.0), ('Shopping', 0.0),
        ('Ships', 0.0), ('Self-Guide', 0.0), ('Scenic Wal', 0.0),
        ('Scenic Rai', 0.0), ('Sacred & R', 0.0), ('Private To', 0.0),
        ('Playground', 0.0), ('Piers & Bo', 0.0), ('Outdoor Ac', 0.0),
        ('Other Outd', 0.0), ('Other Fun ', 0.0), ('Observator', 0.0),
        ('Observatio', 0.0), ('Nightlife', 0.0), ('Night Tour', 0.0),
        ('Neighborho', 0.0), ('National P', 0.0), ('Mines', 0.0),
        ('Military B', 0.0), ('Lookouts', 0.0), ('Literary, ', 0.0),
        ('Lighthouse', 0.0), ('Libraries', 0.0), ('Lessons & ', 0.0),
        ('Islands', 0.0), ('Historic W', 0.0), ('Government', 0.0),
        ('Gift & Spe', 0.0), ('Food & Dri', 0.0), ('Flea & Str', 0.0),
        ('Factory To', 0.0), ('Educationa', 0.0), ('Concerts &', 0.0),
        ('Coffeehous', 0.0), ('Classes & ', 0.0), ('City Tours', 0.0),
        ('Castles', 0.0), ('Bridges', 0.0), ('Bodies of ', 0.0),
        ('Biking Tra', 0.0), ('Battlefiel', 0.0), ('Ballets', 0.0),
        ('Auto Race ', 0.0), ('Art Galler', 0.0)],
       dtype=[('feature', 'S10'), ('importance', '<f8')]),
 array([('RankPercen', 0.06266225594213995), ('Rank', 0.04739976579805334),
        ('review_pol', 0.03947451085555946),
        ('TotalThing', 0.0381469799115917),
        ('quote_sub_', 0.037377531721634195),
        ('review_pol', 0.031844117807274065),
        ('review_pol', 0.030730587539327774),
        ('review_pol', 0.030622952804746844),
        ('quote_sub_', 0.028980796461515756),
        ('quote_pol_', 0.028823043190663578),
        ('review_sub', 0.026537554289123688),
        ('descri_sub', 0.026105656796303334),
        ('quote_pol_', 0.025440997700606018),
        ('review_sub', 0.02531047858626718),
        ('Business_C', 0.024934286578561816),
        ('review_sub', 0.024875042741544687),
        ('ReviewCoun', 0.024289184059331313),
        ('Friends_Co', 0.023882612410230663),
        ('quote_pol_', 0.02336538303410578),
        ('Families_C', 0.022189821140947353),
        ('Couples_Co', 0.021358760350116267),
        ('review_sub', 0.021247612062321102),
        ('Solo_Count', 0.019764239258260558),
        ('quote_pol_', 0.01771344390674527),
        ('descri_pol', 0.01645179093251485),
        ('FeatureCou', 0.011278111916255544),
        ('Country__O', 0.008231751263534742),
        ('a lot of f', 0.007555001378153006),
        ('quote_sub_', 0.007033340642881664),
        ('Country__U', 0.0060918191468948306),
        ('on display', 0.005647369300002437),
        ('worth a vi', 0.005622281270883009),
        ('History Mu', 0.005367780159589957),
        ('gift shop', 0.005024349784028573),
        ('amazing co', 0.004317041494597435),
        ('Libraries', 0.0040510560690890825),
        ('private co', 0.004009267267189645),
        ('all ages', 0.003973091082087132),
        ('Specialty ', 0.0036298194173245077),
        ('moving exp', 0.0036139162506028284),
        ('two hours', 0.0035432679079868044),
        ('Science Mu', 0.003518265213904424),
        ('special ex', 0.003457460018043161),
        ('interestin', 0.003414522019303658),
        ('interactiv', 0.0033111456259880766),
        ('LengthOfVi', 0.003295766644517638),
        ('entrance f', 0.003257732652491592),
        ('exhibits', 0.003241808446338547),
        ('artifacts', 0.0032220142615806994),
        ('galleries', 0.0031008070372800646),
        ('his life', 0.0030727707819349515),
        ('van gogh', 0.0030617625502987224),
        ('informatio', 0.003061169259456113),
        ('history le', 0.0030559369977691585),
        ('rainy day', 0.0030514300648023748),
        ('permanent ', 0.003045076207041568),
        ('Art Museum', 0.0029712788900970863),
        ('history bu', 0.0029642310011391247),
        ('interestin', 0.00291219668452993),
        ('audio tour', 0.002845047210035042),
        ('admission', 0.002810592800953578),
        ('interestin', 0.0027053784740495345),
        ('well worth', 0.002587521565538911),
        ('old west', 0.0025792996926300893),
        ('museums', 0.0025265106090770913),
        ('world war', 0.0024511562255654425),
        ('take your ', 0.0023943546414864616),
        ('great muse', 0.0023914296537231794),
        ('free entry', 0.002364052560902985),
        ('hands on a', 0.002363073981910023),
        ('for sale', 0.0022847819717458392),
        ('worth the ', 0.0022842930934737276),
        ('lots of hi', 0.0022734829098794785),
        ('few hours', 0.0022598648714520332),
        ('great for ', 0.0021665635748735956),
        ('kids and a', 0.002129900410731651),
        ('well worth', 0.0020791763187914857),
        ('Natural Hi', 0.0020668661355844357),
        ('Sights & L', 0.002038530587130368),
        ('Military M', 0.002028785267020304),
        ('extensive ', 0.0019589684229794338),
        ('civil war', 0.0019292883774490615),
        ('small muse', 0.0019212913069502114),
        ('life size', 0.0019207135923893584),
        ('changing e', 0.0019019831303012415),
        ('learn some', 0.001889593306721491),
        ('LengthOfVi', 0.001871547149190033),
        ('local hist', 0.0018331377247339641),
        ('rotating e', 0.0017996564824853847),
        ('quote_sub_', 0.001791157858426952),
        ('great coll', 0.0017670376800322022),
        ('take pictu', 0.0017328113007455165),
        ('works of a', 0.001637861984785835),
        ('couple of ', 0.0016054476287034832),
        ('third floo', 0.001558995316050628),
        ('great hist', 0.0015468817051967378),
        ("Children's", 0.0015138987962884886),
        ('special ex', 0.0015120427675666842),
        ('Cultural T', 0.0015081353529312566),
        ('Nature & P', 0.0014496714547295904),
        ('three hour', 0.0014388359683294165),
        ('sculpture ', 0.0014358676854116048),
        ('second flo', 0.00140131474431342),
        ('free admis', 0.0013523137417905244),
        ('Fee__Yes ', 0.001313653194828185),
        ('interactiv', 0.001285863210977618),
        ('eye openin', 0.0012836896224627293),
        ('Tours', 0.0012658714033978566),
        ('natural hi', 0.0012618191863555319),
        ('Fun & Game', 0.001254429421909663),
        ('Walking To', 0.0012202283968488765),
        ('scavenger ', 0.0012155538159666433),
        ('old master', 0.0011833594385977121),
        ('great plac', 0.0011747164613869743),
        ('displays', 0.0011508644664143352),
        ('short film', 0.001111689698540101),
        ('Gardens', 0.0011089942274884654),
        ('history', 0.0010955691716854972),
        ('chronologi', 0.0010916986874160543),
        ('art lovers', 0.0010848013711990102),
        ('suggested ', 0.0010733091924486392),
        ('Movie Thea', 0.001051567032831364),
        ('audio guid', 0.0009414491743658349),
        ('Museums', 0.0009076971709126094),
        ('step back ', 0.0009069480311094831),
        ('across the', 0.0008932908331153019),
        ('Private To', 0.0008617667858205403),
        ('top floor', 0.0008099572203180881),
        ('Fee__No ', 0.0007940335698635286),
        ('Arenas & S', 0.0007772844201276366),
        ('own pace', 0.0007722500624894938),
        ('early days', 0.0007618772692263248),
        ('Other Fun ', 0.000749417565741486),
        ('traveling ', 0.0007174206748295437),
        ('enjoyed ou', 0.0007001516681150999),
        ('the lower ', 0.0006976859928327625),
        ('beautiful ', 0.0006919372750519569),
        ('guided tou', 0.0006802474781483502),
        ('Traveler R', 0.0006489746648162447),
        ('Architectu', 0.0006462025709230484),
        ('large coll', 0.0006176520589069076),
        ('LengthOfVi', 0.0005940564525758748),
        ('three floo', 0.0005913793764916394),
        ('Mines', 0.0005683042280593342),
        ('Art Galler', 0.0005553680164124762),
        ('Points of ', 0.0005518573112149473),
        ('Shopping', 0.0005467395269993584),
        ('Ships', 0.000515466600002356),
        ('great exhi', 0.0004914466383073851),
        ('we spent h', 0.00048490084721376667),
        ('stuffed an', 0.00048234288739744597),
        ('american h', 0.000357736989223357),
        ('great disp', 0.0003386090089821347),
        ('modern art', 0.00033257693164997517),
        ('Scenic Wal', 0.0003252846061898749),
        ('LengthOfVi', 0.0002838015194985668),
        ('Historic S', 0.0002768619433606404),
        ('nice colle', 0.00026683502851513176),
        ('great plac', 0.00026371385164612076),
        ('Gift & Spe', 0.000226960449192831),
        ('Educationa', 0.00020443165981578825),
        ('entry fee', 0.00019986420764140644),
        ('Sacred & R', 0.0001270020280714123),
        ('collection', 7.499450978402751e-05),
        ('whole fami', 5.019864914922881e-05),
        ('Historic W', 3.011561388870098e-05),
        ('walk aroun', 7.647865088319093e-06),
        ('worth a st', 4.420143996017161e-06), ('self guide', 0.0),
        ('Zoos & Aqu', 0.0), ('Zipline & ', 0.0), ('Wineries &', 0.0),
        ('Volcanos', 0.0), ('Visitor Ce', 0.0), ('Valleys', 0.0),
        ('Transporta', 0.0), ('Tramways', 0.0), ('Theaters', 0.0),
        ('State Park', 0.0), ('Sports Com', 0.0), ('Self-Guide', 0.0),
        ('Scenic Rai', 0.0), ('Playground', 0.0), ('Piers & Bo', 0.0),
        ('Outdoor Ac', 0.0), ('Other Outd', 0.0), ('Observator', 0.0),
        ('Observatio', 0.0), ('Nightlife', 0.0), ('Night Tour', 0.0),
        ('Neighborho', 0.0), ('National P', 0.0), ('Monuments ', 0.0),
        ('Military B', 0.0), ('Lookouts', 0.0), ('Literary, ', 0.0),
        ('Lighthouse', 0.0), ('Lessons & ', 0.0), ('Islands', 0.0),
        ('Historical', 0.0), ('Government', 0.0), ('Geologic F', 0.0),
        ('Food & Dri', 0.0), ('Flea & Str', 0.0), ('Factory To', 0.0),
        ('Concerts &', 0.0), ('Coffeehous', 0.0), ('Classes & ', 0.0),

#### KNN imputation

In [13]:
(museum_p.columns == 'PreciseRating').tolist().index(True)

193

In [14]:
(museum_d.columns == 'Rating').tolist().index(True)

2

In [15]:
# find the best k for imputation for random forest classification 
result_df = cv_rf_class(range(1,10), museum_d,'Rating',[2,193])
result_df
# k should be 7

Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.445
Computing distances for sample #101/1603, elapsed time: 0.595
Computing distances for sample #201/1603, elapsed time: 0.771
Computing distances for sample #301/1603, elapsed time: 0.903
Computing distances for sample #401/1603, elapsed time: 1.055
Computing distances for sample #501/1603, elapsed time: 1.177
Computing distances for sample #601/1603, elapsed time: 1.319
Computing distances for sample #701/1603, elapsed time: 1.442
Computing distances for sample #801/1603, elapsed time: 1.582
Computing distances for sample #901/1603, elapsed time: 1.714
Computing distances for sample #1001/1603, elapsed time: 1.882
Computing distances for sample #1101/1603, elapsed time: 2.005
Computing distances for sample #1201/1603, elapsed time: 2.148
Computing distances for sample #1301/1603, elapsed time: 2.275
Computing distances for sample #1401/1603, elapsed time: 2.438
Computing distances for sample #1501/1603, elapsed time: 2.589
Computing distances for sample #1601/1603, elapsed time: 2.746
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.926
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.927
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.927
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.928
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.929
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.931
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.932
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.934
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.936
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.938
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.940
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.941
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.942
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.944
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.946
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.948
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.949
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.389
Computing distances for sample #101/1603, elapsed time: 0.509
Computing distances for sample #201/1603, elapsed time: 0.644
Computing distances for sample #301/1603, elapsed time: 0.770
Computing distances for sample #401/1603, elapsed time: 0.904
Computing distances for sample #501/1603, elapsed time: 1.024
Computing distances for sample #601/1603, elapsed time: 1.167
Computing distances for sample #701/1603, elapsed time: 1.295
Computing distances for sample #801/1603, elapsed time: 1.431
Computing distances for sample #901/1603, elapsed time: 1.574
Computing distances for sample #1001/1603, elapsed time: 1.729
Computing distances for sample #1101/1603, elapsed time: 1.872
Computing distances for sample #1201/1603, elapsed time: 2.018
Computing distances for sample #1301/1603, elapsed time: 2.168
Computing distances for sample #1401/1603, elapsed time: 2.343
Computing distances for sample #1501/1603, elapsed time: 2.476
Computing distances for sample #1601/1603, elapsed time: 2.614
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.787
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.788
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.789
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.790
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.791
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.793
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.794
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.796
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.798
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.801
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.803
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.805
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.806
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.808
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.810
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.812
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.814
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.512
Computing distances for sample #101/1603, elapsed time: 0.643
Computing distances for sample #201/1603, elapsed time: 0.770
Computing distances for sample #301/1603, elapsed time: 0.897
Computing distances for sample #401/1603, elapsed time: 1.021
Computing distances for sample #501/1603, elapsed time: 1.152
Computing distances for sample #601/1603, elapsed time: 1.274
Computing distances for sample #701/1603, elapsed time: 1.400
Computing distances for sample #801/1603, elapsed time: 1.524
Computing distances for sample #901/1603, elapsed time: 1.649
Computing distances for sample #1001/1603, elapsed time: 1.805
Computing distances for sample #1101/1603, elapsed time: 1.965
Computing distances for sample #1201/1603, elapsed time: 2.112
Computing distances for sample #1301/1603, elapsed time: 2.248
Computing distances for sample #1401/1603, elapsed time: 2.397
Computing distances for sample #1501/1603, elapsed time: 2.563
Computing distances for sample #1601/1603, elapsed time: 2.731
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.901
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.902
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.903
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.904
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.906
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.908
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.911
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.913
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.915
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.918
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.920
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.922
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.923
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.925
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.928
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.930
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.931
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.458
Computing distances for sample #101/1603, elapsed time: 0.613
Computing distances for sample #201/1603, elapsed time: 0.738
Computing distances for sample #301/1603, elapsed time: 0.856
Computing distances for sample #401/1603, elapsed time: 0.986
Computing distances for sample #501/1603, elapsed time: 1.112
Computing distances for sample #601/1603, elapsed time: 1.239
Computing distances for sample #701/1603, elapsed time: 1.363
Computing distances for sample #801/1603, elapsed time: 1.564
Computing distances for sample #901/1603, elapsed time: 1.755
Computing distances for sample #1001/1603, elapsed time: 1.904
Computing distances for sample #1101/1603, elapsed time: 2.038
Computing distances for sample #1201/1603, elapsed time: 2.161
Computing distances for sample #1301/1603, elapsed time: 2.294
Computing distances for sample #1401/1603, elapsed time: 2.418
Computing distances for sample #1501/1603, elapsed time: 2.543
Computing distances for sample #1601/1603, elapsed time: 2.664
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.826
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.827
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.828
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.829
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.830
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.832
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.833
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.835
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.837
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.839
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.841
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.843
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.844
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.846
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.848
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.850
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.852
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.377
Computing distances for sample #101/1603, elapsed time: 0.502
Computing distances for sample #201/1603, elapsed time: 0.624
Computing distances for sample #301/1603, elapsed time: 0.748
Computing distances for sample #401/1603, elapsed time: 0.872
Computing distances for sample #501/1603, elapsed time: 0.992
Computing distances for sample #601/1603, elapsed time: 1.113
Computing distances for sample #701/1603, elapsed time: 1.236
Computing distances for sample #801/1603, elapsed time: 1.359
Computing distances for sample #901/1603, elapsed time: 1.491
Computing distances for sample #1001/1603, elapsed time: 1.613
Computing distances for sample #1101/1603, elapsed time: 1.739
Computing distances for sample #1201/1603, elapsed time: 1.860
Computing distances for sample #1301/1603, elapsed time: 1.979
Computing distances for sample #1401/1603, elapsed time: 2.101
Computing distances for sample #1501/1603, elapsed time: 2.224
Computing distances for sample #1601/1603, elapsed time: 2.368
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.532
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.533
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.534
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.535
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.536
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.538
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.540
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.541
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.544
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.548
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.551
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.552
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.554
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.555
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.557
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.559
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.561
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.406
Computing distances for sample #101/1603, elapsed time: 0.525
Computing distances for sample #201/1603, elapsed time: 0.656
Computing distances for sample #301/1603, elapsed time: 0.787
Computing distances for sample #401/1603, elapsed time: 0.909
Computing distances for sample #501/1603, elapsed time: 1.035
Computing distances for sample #601/1603, elapsed time: 1.157
Computing distances for sample #701/1603, elapsed time: 1.283
Computing distances for sample #801/1603, elapsed time: 1.405
Computing distances for sample #901/1603, elapsed time: 1.530
Computing distances for sample #1001/1603, elapsed time: 1.650
Computing distances for sample #1101/1603, elapsed time: 1.777
Computing distances for sample #1201/1603, elapsed time: 1.913
Computing distances for sample #1301/1603, elapsed time: 2.039
Computing distances for sample #1401/1603, elapsed time: 2.161
Computing distances for sample #1501/1603, elapsed time: 2.286
Computing distances for sample #1601/1603, elapsed time: 2.413
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.574
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.575
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.575
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.576
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.578
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.579
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.581
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.583
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.584
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.587
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.589
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.590
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.592
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.594
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.596
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.598
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.599
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.391
Computing distances for sample #101/1603, elapsed time: 0.520
Computing distances for sample #201/1603, elapsed time: 0.642
Computing distances for sample #301/1603, elapsed time: 0.767
Computing distances for sample #401/1603, elapsed time: 0.897
Computing distances for sample #501/1603, elapsed time: 1.019
Computing distances for sample #601/1603, elapsed time: 1.143
Computing distances for sample #701/1603, elapsed time: 1.264
Computing distances for sample #801/1603, elapsed time: 1.386
Computing distances for sample #901/1603, elapsed time: 1.504
Computing distances for sample #1001/1603, elapsed time: 1.636
Computing distances for sample #1101/1603, elapsed time: 1.755
Computing distances for sample #1201/1603, elapsed time: 1.880
Computing distances for sample #1301/1603, elapsed time: 2.003
Computing distances for sample #1401/1603, elapsed time: 2.130
Computing distances for sample #1501/1603, elapsed time: 2.257
Computing distances for sample #1601/1603, elapsed time: 2.387
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.548
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.549
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.550
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.551
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.552
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.554
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.555
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.557
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.559
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.561
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.563
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.565
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.566
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.568
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.570
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.572
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.574
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.399
Computing distances for sample #101/1603, elapsed time: 0.532
Computing distances for sample #201/1603, elapsed time: 0.685
Computing distances for sample #301/1603, elapsed time: 0.817
Computing distances for sample #401/1603, elapsed time: 0.946
Computing distances for sample #501/1603, elapsed time: 1.068
Computing distances for sample #601/1603, elapsed time: 1.196
Computing distances for sample #701/1603, elapsed time: 1.315
Computing distances for sample #801/1603, elapsed time: 1.438
Computing distances for sample #901/1603, elapsed time: 1.559
Computing distances for sample #1001/1603, elapsed time: 1.689
Computing distances for sample #1101/1603, elapsed time: 1.811
Computing distances for sample #1201/1603, elapsed time: 1.932
Computing distances for sample #1301/1603, elapsed time: 2.063
Computing distances for sample #1401/1603, elapsed time: 2.195
Computing distances for sample #1501/1603, elapsed time: 2.318
Computing distances for sample #1601/1603, elapsed time: 2.443
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.601
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.602
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.603
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.604
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.605
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.607
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.608
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.610
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.612
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.614
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.617
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.618
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.620
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.622
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.624
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.626
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.627
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.413
Computing distances for sample #101/1603, elapsed time: 0.557
Computing distances for sample #201/1603, elapsed time: 0.721
Computing distances for sample #301/1603, elapsed time: 0.870
Computing distances for sample #401/1603, elapsed time: 1.027
Computing distances for sample #501/1603, elapsed time: 1.181
Computing distances for sample #601/1603, elapsed time: 1.337
Computing distances for sample #701/1603, elapsed time: 1.457
Computing distances for sample #801/1603, elapsed time: 1.580
Computing distances for sample #901/1603, elapsed time: 1.705
Computing distances for sample #1001/1603, elapsed time: 1.828
Computing distances for sample #1101/1603, elapsed time: 1.952
Computing distances for sample #1201/1603, elapsed time: 2.083
Computing distances for sample #1301/1603, elapsed time: 2.210
Computing distances for sample #1401/1603, elapsed time: 2.345
Computing distances for sample #1501/1603, elapsed time: 2.476
Computing distances for sample #1601/1603, elapsed time: 2.602
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.789
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.790
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.791
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.792
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.793
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.795
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.797
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.799
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.801
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.803
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.806
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.807
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.809
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.812
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.814

      error  k     score
6  0.255452  7  0.982839
8  0.258567  9  0.981279
3  0.261682  4  0.985179
7  0.261682  8  0.982839
0  0.267913  1  0.982059
2  0.271028  3  0.978939
4  0.274143  5  0.982839
5  0.274143  6  0.980499
1  0.280374  2  0.982059

In [16]:
# find the best k for imputation for random forest regression 
result_df2 = cv_rf_regres(range(1,10), museum_p,'PreciseRating',[2,193])
result_df2 # k should be 9

Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.407
Computing distances for sample #101/1603, elapsed time: 0.530
Computing distances for sample #201/1603, elapsed time: 0.664
Computing distances for sample #301/1603, elapsed time: 0.797
Computing distances for sample #401/1603, elapsed time: 0.918
Computing distances for sample #501/1603, elapsed time: 1.037
Computing distances for sample #601/1603, elapsed time: 1.159
Computing distances for sample #701/1603, elapsed time: 1.285
Computing distances for sample #801/1603, elapsed time: 1.410
Computing distances for sample #901/1603, elapsed time: 1.535
Computing distances for sample #1001/1603, elapsed time: 1.658
Computing distances for sample #1101/1603, elapsed time: 1.779
Computing distances for sample #1201/1603, elapsed time: 1.905
Computing distances for sample #1301/1603, elapsed time: 2.024
Computing distances for sample #1401/1603, elapsed time: 2.144
Computing distances for sample #1501/1603, elapsed time: 2.268
Computing distances for sample #1601/1603, elapsed time: 2.388
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.548
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.549
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.549
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.550
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.551
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.553
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.554
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.556
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.557
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.560
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.562
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.563
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.564
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.566
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.568
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.569
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.571
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.376
Computing distances for sample #101/1603, elapsed time: 0.510
Computing distances for sample #201/1603, elapsed time: 0.646
Computing distances for sample #301/1603, elapsed time: 0.776
Computing distances for sample #401/1603, elapsed time: 0.917
Computing distances for sample #501/1603, elapsed time: 1.050
Computing distances for sample #601/1603, elapsed time: 1.175
Computing distances for sample #701/1603, elapsed time: 1.296
Computing distances for sample #801/1603, elapsed time: 1.421
Computing distances for sample #901/1603, elapsed time: 1.544
Computing distances for sample #1001/1603, elapsed time: 1.670
Computing distances for sample #1101/1603, elapsed time: 1.789
Computing distances for sample #1201/1603, elapsed time: 1.911
Computing distances for sample #1301/1603, elapsed time: 2.031
Computing distances for sample #1401/1603, elapsed time: 2.152
Computing distances for sample #1501/1603, elapsed time: 2.292
Computing distances for sample #1601/1603, elapsed time: 2.419
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.581
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.581
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.582
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.583
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.585
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.587
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.588
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.590
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.592
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.594
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.596
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.598
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.599
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.601
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.603
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.605
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.607
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.385
Computing distances for sample #101/1603, elapsed time: 0.513
Computing distances for sample #201/1603, elapsed time: 0.636
Computing distances for sample #301/1603, elapsed time: 0.766
Computing distances for sample #401/1603, elapsed time: 0.887
Computing distances for sample #501/1603, elapsed time: 1.011
Computing distances for sample #601/1603, elapsed time: 1.137
Computing distances for sample #701/1603, elapsed time: 1.258
Computing distances for sample #801/1603, elapsed time: 1.380
Computing distances for sample #901/1603, elapsed time: 1.505
Computing distances for sample #1001/1603, elapsed time: 1.635
Computing distances for sample #1101/1603, elapsed time: 1.763
Computing distances for sample #1201/1603, elapsed time: 1.890
Computing distances for sample #1301/1603, elapsed time: 2.011
Computing distances for sample #1401/1603, elapsed time: 2.140
Computing distances for sample #1501/1603, elapsed time: 2.262
Computing distances for sample #1601/1603, elapsed time: 2.382
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.541
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.542
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.543
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.544
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.545
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.547
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.548
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.550
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.552
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.554
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.557
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.558
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.559
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.561
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.563
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.565
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.567
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.388
Computing distances for sample #101/1603, elapsed time: 0.508
Computing distances for sample #201/1603, elapsed time: 0.634
Computing distances for sample #301/1603, elapsed time: 0.754
Computing distances for sample #401/1603, elapsed time: 0.874
Computing distances for sample #501/1603, elapsed time: 0.993
Computing distances for sample #601/1603, elapsed time: 1.118
Computing distances for sample #701/1603, elapsed time: 1.240
Computing distances for sample #801/1603, elapsed time: 1.363
Computing distances for sample #901/1603, elapsed time: 1.483
Computing distances for sample #1001/1603, elapsed time: 1.609
Computing distances for sample #1101/1603, elapsed time: 1.731
Computing distances for sample #1201/1603, elapsed time: 1.856
Computing distances for sample #1301/1603, elapsed time: 1.975
Computing distances for sample #1401/1603, elapsed time: 2.101
Computing distances for sample #1501/1603, elapsed time: 2.225
Computing distances for sample #1601/1603, elapsed time: 2.352
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.532
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.533
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.534
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.535
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.536
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.538
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.539
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.541
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.543
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.545
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.548
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.549
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.550
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.552
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.554
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.556
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.559
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.377
Computing distances for sample #101/1603, elapsed time: 0.498
Computing distances for sample #201/1603, elapsed time: 0.617
Computing distances for sample #301/1603, elapsed time: 0.736
Computing distances for sample #401/1603, elapsed time: 0.859
Computing distances for sample #501/1603, elapsed time: 0.980
Computing distances for sample #601/1603, elapsed time: 1.101
Computing distances for sample #701/1603, elapsed time: 1.226
Computing distances for sample #801/1603, elapsed time: 1.349
Computing distances for sample #901/1603, elapsed time: 1.471
Computing distances for sample #1001/1603, elapsed time: 1.596
Computing distances for sample #1101/1603, elapsed time: 1.715
Computing distances for sample #1201/1603, elapsed time: 1.836
Computing distances for sample #1301/1603, elapsed time: 1.957
Computing distances for sample #1401/1603, elapsed time: 2.084
Computing distances for sample #1501/1603, elapsed time: 2.210
Computing distances for sample #1601/1603, elapsed time: 2.332
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.491
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.492
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.493
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.494
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.495
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.497
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.499
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.500
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.502
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.504
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.507
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.508
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.510
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.511
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.514
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.516
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.517
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.375
Computing distances for sample #101/1603, elapsed time: 0.496
Computing distances for sample #201/1603, elapsed time: 0.618
Computing distances for sample #301/1603, elapsed time: 0.739
Computing distances for sample #401/1603, elapsed time: 0.862
Computing distances for sample #501/1603, elapsed time: 0.986
Computing distances for sample #601/1603, elapsed time: 1.109
Computing distances for sample #701/1603, elapsed time: 1.233
Computing distances for sample #801/1603, elapsed time: 1.355
Computing distances for sample #901/1603, elapsed time: 1.486
Computing distances for sample #1001/1603, elapsed time: 1.611
Computing distances for sample #1101/1603, elapsed time: 1.735
Computing distances for sample #1201/1603, elapsed time: 1.862
Computing distances for sample #1301/1603, elapsed time: 1.984
Computing distances for sample #1401/1603, elapsed time: 2.109
Computing distances for sample #1501/1603, elapsed time: 2.231
Computing distances for sample #1601/1603, elapsed time: 2.353
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.511
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.512
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.513
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.514
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.516
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.517
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.519
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.520
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.522
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.525
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.527
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.528
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.530
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.532
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.534
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.536
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.537
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.396
Computing distances for sample #101/1603, elapsed time: 0.516
Computing distances for sample #201/1603, elapsed time: 0.643
Computing distances for sample #301/1603, elapsed time: 0.777
Computing distances for sample #401/1603, elapsed time: 0.915
Computing distances for sample #501/1603, elapsed time: 1.046
Computing distances for sample #601/1603, elapsed time: 1.168
Computing distances for sample #701/1603, elapsed time: 1.297
Computing distances for sample #801/1603, elapsed time: 1.418
Computing distances for sample #901/1603, elapsed time: 1.539
Computing distances for sample #1001/1603, elapsed time: 1.673
Computing distances for sample #1101/1603, elapsed time: 1.799
Computing distances for sample #1201/1603, elapsed time: 1.920
Computing distances for sample #1301/1603, elapsed time: 2.042
Computing distances for sample #1401/1603, elapsed time: 2.167
Computing distances for sample #1501/1603, elapsed time: 2.290
Computing distances for sample #1601/1603, elapsed time: 2.412
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.592
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.593
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.594
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.595
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.597
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.599
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.601
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.603
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.605
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.607
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.610
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.611
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.612
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.614
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.616
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.618
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.620
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.372
Computing distances for sample #101/1603, elapsed time: 0.491
Computing distances for sample #201/1603, elapsed time: 0.611
Computing distances for sample #301/1603, elapsed time: 0.731
Computing distances for sample #401/1603, elapsed time: 0.854
Computing distances for sample #501/1603, elapsed time: 0.978
Computing distances for sample #601/1603, elapsed time: 1.099
Computing distances for sample #701/1603, elapsed time: 1.245
Computing distances for sample #801/1603, elapsed time: 1.387
Computing distances for sample #901/1603, elapsed time: 1.507
Computing distances for sample #1001/1603, elapsed time: 1.635
Computing distances for sample #1101/1603, elapsed time: 1.755
Computing distances for sample #1201/1603, elapsed time: 1.889
Computing distances for sample #1301/1603, elapsed time: 2.013
Computing distances for sample #1401/1603, elapsed time: 2.137
Computing distances for sample #1501/1603, elapsed time: 2.258
Computing distances for sample #1601/1603, elapsed time: 2.385
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.544
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.544
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.545
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.546
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.548
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.549
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.551
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.553
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.554
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.557
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.559
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.560
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.562
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.563
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.566
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.568
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.569
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.373
Computing distances for sample #101/1603, elapsed time: 0.495
Computing distances for sample #201/1603, elapsed time: 0.618
Computing distances for sample #301/1603, elapsed time: 0.742
Computing distances for sample #401/1603, elapsed time: 0.868
Computing distances for sample #501/1603, elapsed time: 0.988
Computing distances for sample #601/1603, elapsed time: 1.110
Computing distances for sample #701/1603, elapsed time: 1.229
Computing distances for sample #801/1603, elapsed time: 1.360
Computing distances for sample #901/1603, elapsed time: 1.489
Computing distances for sample #1001/1603, elapsed time: 1.616
Computing distances for sample #1101/1603, elapsed time: 1.735
Computing distances for sample #1201/1603, elapsed time: 1.861
Computing distances for sample #1301/1603, elapsed time: 1.986
Computing distances for sample #1401/1603, elapsed time: 2.113
Computing distances for sample #1501/1603, elapsed time: 2.247
Computing distances for sample #1601/1603, elapsed time: 2.374
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.551
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.552
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.553
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.554
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.555
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.557
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.559
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.562
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.565
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.568
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.571
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.573
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.574
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.576
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.578

   k       mse     score
8  9  0.039745  0.891566
1  2  0.040008  0.893849
2  3  0.040060  0.895123
6  7  0.040258  0.891312
3  4  0.040287  0.891619
0  1  0.040399  0.892123
5  6  0.040425  0.893037
7  8  0.040432  0.893838
4  5  0.040840  0.892122

In [17]:
# find the best k for imputation for random forest regression 
result_df3 = cv_rf_regres(range(1,10), museum_d,'Rating',[2,193])
result_df3
# k should be 1??

Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.386
Computing distances for sample #101/1603, elapsed time: 0.505
Computing distances for sample #201/1603, elapsed time: 0.628
Computing distances for sample #301/1603, elapsed time: 0.747
Computing distances for sample #401/1603, elapsed time: 0.873
Computing distances for sample #501/1603, elapsed time: 0.995
Computing distances for sample #601/1603, elapsed time: 1.116
Computing distances for sample #701/1603, elapsed time: 1.238
Computing distances for sample #801/1603, elapsed time: 1.360
Computing distances for sample #901/1603, elapsed time: 1.486
Computing distances for sample #1001/1603, elapsed time: 1.608
Computing distances for sample #1101/1603, elapsed time: 1.728
Computing distances for sample #1201/1603, elapsed time: 1.849
Computing distances for sample #1301/1603, elapsed time: 1.969
Computing distances for sample #1401/1603, elapsed time: 2.091
Computing distances for sample #1501/1603, elapsed time: 2.215
Computing distances for sample #1601/1603, elapsed time: 2.335
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.503
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.503
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.504
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.505
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.506
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.508
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.509
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.511
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.512
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.514
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.517
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.518
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.519
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.521
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.522
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.524
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.526
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.383
Computing distances for sample #101/1603, elapsed time: 0.503
Computing distances for sample #201/1603, elapsed time: 0.627
Computing distances for sample #301/1603, elapsed time: 0.746
Computing distances for sample #401/1603, elapsed time: 0.868
Computing distances for sample #501/1603, elapsed time: 0.987
Computing distances for sample #601/1603, elapsed time: 1.107
Computing distances for sample #701/1603, elapsed time: 1.227
Computing distances for sample #801/1603, elapsed time: 1.349
Computing distances for sample #901/1603, elapsed time: 1.469
Computing distances for sample #1001/1603, elapsed time: 1.592
Computing distances for sample #1101/1603, elapsed time: 1.710
Computing distances for sample #1201/1603, elapsed time: 1.836
Computing distances for sample #1301/1603, elapsed time: 1.955
Computing distances for sample #1401/1603, elapsed time: 2.076
Computing distances for sample #1501/1603, elapsed time: 2.206
Computing distances for sample #1601/1603, elapsed time: 2.328
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.496
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.497
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.499
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.500
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.501
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.503
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.504
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.506
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.508
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.510
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.512
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.514
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.515
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.518
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.520
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.522
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.523
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.373
Computing distances for sample #101/1603, elapsed time: 0.494
Computing distances for sample #201/1603, elapsed time: 0.626
Computing distances for sample #301/1603, elapsed time: 0.764
Computing distances for sample #401/1603, elapsed time: 0.886
Computing distances for sample #501/1603, elapsed time: 1.011
Computing distances for sample #601/1603, elapsed time: 1.133
Computing distances for sample #701/1603, elapsed time: 1.252
Computing distances for sample #801/1603, elapsed time: 1.381
Computing distances for sample #901/1603, elapsed time: 1.507
Computing distances for sample #1001/1603, elapsed time: 1.633
Computing distances for sample #1101/1603, elapsed time: 1.752
Computing distances for sample #1201/1603, elapsed time: 1.873
Computing distances for sample #1301/1603, elapsed time: 1.999
Computing distances for sample #1401/1603, elapsed time: 2.120
Computing distances for sample #1501/1603, elapsed time: 2.239
Computing distances for sample #1601/1603, elapsed time: 2.363
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.523
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.523
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.524
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.525
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.527
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.528
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.530
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.532
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.533
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.536
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.538
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.540
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.541
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.543
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.545
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.547
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.549
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.374
Computing distances for sample #101/1603, elapsed time: 0.497
Computing distances for sample #201/1603, elapsed time: 0.619
Computing distances for sample #301/1603, elapsed time: 0.746
Computing distances for sample #401/1603, elapsed time: 0.890
Computing distances for sample #501/1603, elapsed time: 1.018
Computing distances for sample #601/1603, elapsed time: 1.141
Computing distances for sample #701/1603, elapsed time: 1.269
Computing distances for sample #801/1603, elapsed time: 1.393
Computing distances for sample #901/1603, elapsed time: 1.521
Computing distances for sample #1001/1603, elapsed time: 1.650
Computing distances for sample #1101/1603, elapsed time: 1.771
Computing distances for sample #1201/1603, elapsed time: 1.894
Computing distances for sample #1301/1603, elapsed time: 2.022
Computing distances for sample #1401/1603, elapsed time: 2.147
Computing distances for sample #1501/1603, elapsed time: 2.272
Computing distances for sample #1601/1603, elapsed time: 2.401
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.558
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.559
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.560
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.561
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.562
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.564
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.565
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.567
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.569
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.571
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.574
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.575
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.576
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.578
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.581
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.583
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.584
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.385
Computing distances for sample #101/1603, elapsed time: 0.507
Computing distances for sample #201/1603, elapsed time: 0.633
Computing distances for sample #301/1603, elapsed time: 0.752
Computing distances for sample #401/1603, elapsed time: 0.877
Computing distances for sample #501/1603, elapsed time: 0.997
Computing distances for sample #601/1603, elapsed time: 1.117
Computing distances for sample #701/1603, elapsed time: 1.236
Computing distances for sample #801/1603, elapsed time: 1.358
Computing distances for sample #901/1603, elapsed time: 1.479
Computing distances for sample #1001/1603, elapsed time: 1.605
Computing distances for sample #1101/1603, elapsed time: 1.727
Computing distances for sample #1201/1603, elapsed time: 1.848
Computing distances for sample #1301/1603, elapsed time: 1.971
Computing distances for sample #1401/1603, elapsed time: 2.097
Computing distances for sample #1501/1603, elapsed time: 2.219
Computing distances for sample #1601/1603, elapsed time: 2.346
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.506
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.507
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.508
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.509
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.510
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.512
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.513
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.515
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.517
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.519
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.522
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.523
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.524
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.526
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.528
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.530
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.532
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.385
Computing distances for sample #101/1603, elapsed time: 0.512
Computing distances for sample #201/1603, elapsed time: 0.633
Computing distances for sample #301/1603, elapsed time: 0.753
Computing distances for sample #401/1603, elapsed time: 0.875
Computing distances for sample #501/1603, elapsed time: 1.026
Computing distances for sample #601/1603, elapsed time: 1.222
Computing distances for sample #701/1603, elapsed time: 1.430
Computing distances for sample #801/1603, elapsed time: 1.634
Computing distances for sample #901/1603, elapsed time: 1.761
Computing distances for sample #1001/1603, elapsed time: 1.889
Computing distances for sample #1101/1603, elapsed time: 2.010
Computing distances for sample #1201/1603, elapsed time: 2.131
Computing distances for sample #1301/1603, elapsed time: 2.259
Computing distances for sample #1401/1603, elapsed time: 2.381
Computing distances for sample #1501/1603, elapsed time: 2.508
Computing distances for sample #1601/1603, elapsed time: 2.630
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.788
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.789
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.790
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.791
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.792
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.794
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.795
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.799
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.802
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.806
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.808
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.810
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.812
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.814
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.816
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.818
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.819
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.436
Computing distances for sample #101/1603, elapsed time: 0.560
Computing distances for sample #201/1603, elapsed time: 0.682
Computing distances for sample #301/1603, elapsed time: 0.807
Computing distances for sample #401/1603, elapsed time: 0.934
Computing distances for sample #501/1603, elapsed time: 1.053
Computing distances for sample #601/1603, elapsed time: 1.181
Computing distances for sample #701/1603, elapsed time: 1.302
Computing distances for sample #801/1603, elapsed time: 1.425
Computing distances for sample #901/1603, elapsed time: 1.544
Computing distances for sample #1001/1603, elapsed time: 1.669
Computing distances for sample #1101/1603, elapsed time: 1.794
Computing distances for sample #1201/1603, elapsed time: 1.919
Computing distances for sample #1301/1603, elapsed time: 2.039
Computing distances for sample #1401/1603, elapsed time: 2.164
Computing distances for sample #1501/1603, elapsed time: 2.284
Computing distances for sample #1601/1603, elapsed time: 2.406
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.573
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.574
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.574
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.576
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.577
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.579
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.580
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.582
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.584
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.586
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.589
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.590
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.592
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.593
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.596
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.598
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.599
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.379
Computing distances for sample #101/1603, elapsed time: 0.499
Computing distances for sample #201/1603, elapsed time: 0.627
Computing distances for sample #301/1603, elapsed time: 0.747
Computing distances for sample #401/1603, elapsed time: 0.870
Computing distances for sample #501/1603, elapsed time: 1.000
Computing distances for sample #601/1603, elapsed time: 1.122
Computing distances for sample #701/1603, elapsed time: 1.244
Computing distances for sample #801/1603, elapsed time: 1.366
Computing distances for sample #901/1603, elapsed time: 1.487
Computing distances for sample #1001/1603, elapsed time: 1.611
Computing distances for sample #1101/1603, elapsed time: 1.738
Computing distances for sample #1201/1603, elapsed time: 1.868
Computing distances for sample #1301/1603, elapsed time: 1.989
Computing distances for sample #1401/1603, elapsed time: 2.112
Computing distances for sample #1501/1603, elapsed time: 2.236
Computing distances for sample #1601/1603, elapsed time: 2.361
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.520
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.521
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.522
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.523
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.524
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.526
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.527
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.529
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.531
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.533
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.536
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.537
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.538
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.540
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.543
Imputing row 1501/1603 with 0 missing columns, elapsed time: 2.545
Imputing row 1601/1603 with 0 missing columns, elapsed time: 2.546
Computing pairwise distances between 1603 samples
Computing distances for sample #1/1603, elapsed time: 0.447
Computing distances for sample #101/1603, elapsed time: 0.571
Computing distances for sample #201/1603, elapsed time: 0.692
Computing distances for sample #301/1603, elapsed time: 0.815
Computing distances for sample #401/1603, elapsed time: 0.938
Computing distances for sample #501/1603, elapsed time: 1.059
Computing distances for sample #601/1603, elapsed time: 1.182
Computing distances for sample #701/1603, elapsed time: 1.306
Computing distances for sample #801/1603, elapsed time: 1.430
Computing distances for sample #901/1603, elapsed time: 1.552
Computing distances for sample #1001/1603, elapsed time: 1.674
Computing distances for sample #1101/1603, elapsed time: 1.797
Computing distances for sample #1201/1603, elapsed time: 1.920
Computing distances for sample #1301/1603, elapsed time: 2.049
Computing distances for sample #1401/1603, elapsed time: 2.172
Computing distances for sample #1501/1603, elapsed time: 2.309
Computing distances for sample #1601/1603, elapsed time: 2.431
Imputing row 1/1603 with 0 missing columns, elapsed time: 2.590
Imputing row 101/1603 with 2 missing columns, elapsed time: 2.591
Imputing row 201/1603 with 0 missing columns, elapsed time: 2.592
Imputing row 301/1603 with 0 missing columns, elapsed time: 2.593
Imputing row 401/1603 with 2 missing columns, elapsed time: 2.594
Imputing row 501/1603 with 0 missing columns, elapsed time: 2.596
Imputing row 601/1603 with 0 missing columns, elapsed time: 2.597
Imputing row 701/1603 with 0 missing columns, elapsed time: 2.599
Imputing row 801/1603 with 2 missing columns, elapsed time: 2.601
Imputing row 901/1603 with 0 missing columns, elapsed time: 2.603
Imputing row 1001/1603 with 0 missing columns, elapsed time: 2.606
Imputing row 1101/1603 with 0 missing columns, elapsed time: 2.607
Imputing row 1201/1603 with 0 missing columns, elapsed time: 2.609
Imputing row 1301/1603 with 2 missing columns, elapsed time: 2.610
Imputing row 1401/1603 with 0 missing columns, elapsed time: 2.612

   k       mse     score
0  1  0.056176  0.873865
2  3  0.056262  0.875629
1  2  0.057111  0.875464
6  7  0.057383  0.872220
7  8  0.057921  0.873278
8  9  0.057960  0.874383
4  5  0.058100  0.873395
5  6  0.058115  0.871256
3  4  0.058364  0.872690

### Classification - KNN

In [80]:
# from sklearn import neighbors
# from sklearn import grid_search

# knn = neighbors.KNeighborsClassifier()
# grid_param = {'weights': ['uniform', 'distance'], 'n_neighbors': range(3, 20), 'p': [1, 2]}

# # Drop rating column
# m_x = mean_impute_d.drop(mean_impute_d.columns[[2]], axis=1) 
# # Convert the rating into string for classification
# m_y = [str(i) for i in mean_impute_d['Rating']]
# # subset training and testing
# x_train, x_test, y_train, y_test = train_test_split(m_x, m_y, test_size=0.2, random_state = 5)

# para_search = grid_search.GridSearchCV(knn, grid_param, scoring='accuracy', cv =5).fit(x_train, y_train)
# print 'best score in grid search:', para_search.best_score_
# print 'best parameters:', para_search.best_params_
# knn_best = para_search.best_estimator_
# knn_best.fit(x_train, y_train)
# print 'best knn score:', knn_best.score(x_train, y_train)
# predicted = knn_best.predict(x_test)
# print 'error rate', 1 - np.mean(predicted == y_test)
# #  p = 1, this is equivalent to using manhattan_distance (l1), and euclidean_distance (l2) for p = 2

In [81]:
# # check how the data was split into training and test sets
# print 'Rating Distribution:'
# print 'whole data:\n', museum_d['Rating'].value_counts()
# print '-'*20
# print 'train data:\n', pd.Series(y_train).value_counts()
# print '-'*20
# print 'test data:\n', pd.Series(y_test).value_counts()

In [28]:
pd.DataFrame({'colname':museum_p.columns.values})

                               colname
0                         FeatureCount
1                                 Rank
2                          ReviewCount
3                      TotalThingsToDo
4                       RankPercentage
5                        Ancient Ruins
6              Architectural Buildings
7                    Arenas & Stadiums
8                        Art Galleries
9                          Art Museums
10                    Auto Race Tracks
11                             Ballets
12                        Battlefields
13                       Biking Trails
14                     Bodies of Water
15                             Bridges
16                             Castles
17                          Cemeteries
18                  Children's Museums
19                          City Tours
20                 Classes & Workshops
21                        Coffeehouses
22                    Concerts & Shows
23                      Cultural Tours
24                   Educational sites
25                       Factory Tours
26               Flea & Street Markets
27                        Food & Drink
28                         Fun & Games
29                             Gardens
..                                 ...
190                         Solo_Count
191                     Business_Count
192                      Friends_Count
193                      PreciseRating
194                      quote_pol_var
195                     quote_pol_mean
196                      quote_pol_max
197                      quote_pol_min
198                      quote_sub_var
199                     quote_sub_mean
200                      quote_sub_max
201                      quote_sub_min
202                     review_pol_var
203                    review_pol_mean
204                     review_pol_max
205                     review_pol_min
206                     review_sub_var
207                    review_sub_mean
208                     review_sub_max
209                     review_sub_min
210                         descri_pol
211                         descri_sub
212          LengthOfVisit__1-2 hours
213          LengthOfVisit__2-3 hours
214            LengthOfVisit__<1 hour
215  LengthOfVisit__More than 3 hours
216                     Country__Other
217                       Country__USA
218                           Fee__No
219                          Fee__Yes

[220 rows x 1 columns]